contigua:
	gcc -c lista_contigua.c
	gcc main.c lista_contigua.o -o execute
	./execute

encadeada:
	gcc -c lista_encadeada.c
	gcc main.c lista_encadeada.o -o execute
	./execute

remove:
	rm *.o
	rm execute