contigua:	
	gcc -c fila_contigua.c
	gcc main.c fila_contigua.o -o execute
	./execute
	
encadeada:
	gcc -c fila_encadeada.c
	gcc main.c fila_encadeada.o -o execute
	./execute

clean:
	rm *.o
	rm execute